config/routes.rb
Rails.application.routes.draw do
  get 'genres/add_profile'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  get 'terms', to: 'terms#index' 
  root to: 'home#index'
  resources :movies
  resources :genres do
    member do
      get 'add_profile'
    end
  end
  resources :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]
  validates :name, :birthday, presence: true
  after_create :build_initial_profiles

  has_many :profiles, dependent: :destroy
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end


  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        if user.email.blank?
        user.email = data["email"] 
        end
      end
    end
  end

  protected

  def build_initial_profiles
    4.times.each do |t|
      self.profiles.build(name: "Perfil #{t+1}").save
    end
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :set_search
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout :layout_by_resource

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :birthday])
  end
  
  def set_search
    @q = Movie.order('created_at desc').ransack(params[:q])
  end

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def add_profile

    render nothing: true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @genres = Tmdb::Genre.list
    @popular_movies = Tmdb::Movie.popular[0..3]
    @top_rated_movies = Tmdb::Movie.top_rated[0..3]
    @profiles = current_user.profiles
    
    # @search = Tmdb::Search.new
    # @search.resource('genre')
    # @search.query(@genres.pluck(:identification).sample)
    
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def poster_image_url(poster_image)
    "http://image.tmdb.org/t/p/w185//#{poster_image}"
  end
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/genres/add_profile.html.haml
%h1 Genres#add_profile
%p Find me in app/views/genres/add_profile.html.haml

app/views/home/index.html.haml
/ Header
%header.masthead
  .container
    .intro-text
      .intro-lead-in Entendiado(a), procurando algo mais?
      .intro-heading.text-uppercase Já chegou a solução
      %a.btn.btn-secondary.btn-xl.text-uppercase.js-scroll-trigger{href: "#services"} Saber mais...
/ Portfolio Grid
%section#portfolio.bg-light.page-section
  .container
    .row
      .col-lg-12.text-center
        %h2.section-heading.text-uppercase Perfils
        %h3.section-subheading.text-muted Uma lista de filmes personalizada para cada Perfil, assim gaste menos tempo escolhendo o que gostaria de assistir.
    .row
      - @profiles.each_with_index do |profile, index|
        .col-md-6.portfolio-item
          = link_to "##{profile.slug}", class: 'portfolio-link', data: {toggle: 'modal'} do
            .portfolio-hover
              .portfolio-hover-content
                %i.fas.fa-plus.fa-3x
            %img.img-fluid= image_tag "profile-image-#{index}.png", class: 'img-fluid'
          .portfolio-caption
            %h4= profile.name

/ Services
%section#services.page-section
  .container
    .row
      .col-lg-12.text-center
        %h2.section-heading.text-uppercase Categorias
        %p.text-muted Cada Perfil terá sugestões de Filmes a partir das Categorias adicionadas a ele.
        %p.text-muted Escolha um dos Perfis e clique em Adicionar, assim os Filmes e Sugestões estarão no Perfil escolhido.
    %div#genres_list.row.text-center
      - @genres['genres'].each do |genre|
        .col-md-4.mb-10
          %h4.service-heading=genre['name']
          %p
            %select.form-control{url: "#{add_profile_genre_path(genre['id'])}"}
              %option Escolha um Perfil para esta Categoria
              - @profiles.each do |profile|
                =content_tag :option, "Adicionar ao perfil: #{profile.name}", value: profile.slug

/ About
%section#about.page-section
  .container
    .row
      .col-lg-12.text-center
        %h2.section-heading.text-uppercase Lançamentos
        %h3.section-subheading.text-muted Lançamentos, novidades e sugestões para você assistir
    .row
      .col-lg-12
        %ul.timeline
          - @popular_movies.each_with_index do |movie, index|
            %li{class: "#{'timeline-inverted' if index.odd?}"}
              .timeline-image
                %img.img-fluid.rounded-circle.poster-image-size{src: "#{poster_image_url(movie.poster_path)}"}/
              .timeline-panel
                .timeline-heading
                  %h4=movie.release_date
                  %h4.subheading=movie.title
                .timeline-body
                  %p.text-muted{"data-toggle" => "tooltip", "title" => "#{movie.overview}"}= truncate(movie.overview, length: 100)

/ Team
%section#team.bg-light.page-section
  .container
    .row
      .col-lg-12.text-center
        %h2.section-heading.text-uppercase Mais votados
        %h3.section-subheading.text-muted Os que estão realmente em alta pelos usuários!
    .row
      - @top_rated_movies.each do |movie|
        .col-sm-3
          .team-member
            %img.mx-auto.rounded-circle{src: "#{poster_image_url(movie.poster_path)}"}/
            %h5{"data-toggle" => "tooltip", "title" => "#{movie.title}"}= truncate(movie.title, length: 20)
            %p.text-muted
              Média de votos
              ="#{movie.vote_average} (total: #{movie.vote_count})"

/ Contact
%section#contact.page-section
  .container
    .row
      .col-lg-12.text-center
        %h2.section-heading.text-uppercase Meus dados
    .row
      .col-lg-12
        %form#contactForm{name: "sentMessage", novalidate: "novalidate"}
          .row
            .col-md-6
              .form-group
                %input#name.form-control{"data-validation-required-message" => "Please enter your name.", placeholder: "Nome *", required: "required", type: "text"}/
                %p.help-block.text-danger
              .form-group
                %input#email.form-control{"data-validation-required-message" => "Please enter your email address.", placeholder: "Seu email *", required: "required", type: "email"}/
                %p.help-block.text-danger
              .form-group
                %input#birthday.form-control{"data-validation-required-message" => "Please enter your email address.", placeholder: "Data de Nascimento *", required: "required", type: "date"}/
                %p.help-block.text-danger
            .col-md-6
              .form-group
                %input#password.form-control{"data-validation-required-message" => "Please enter your phone number.", placeholder: "Sua senha *", required: "required", type: "password"}/
                %p.help-block.text-danger
              .form-group
                %input#password_confirmation.form-control{"data-validation-required-message" => "Please enter your phone number.", placeholder: "Confirme sua senha *", required: "required", type: "password"}/
                %p.help-block.text-danger
              .form-group
                %input#current_password.form-control{"data-validation-required-message" => "Please enter your phone number.", placeholder: "Senha atual *", required: "required", type: "password"}/
                %p.help-block.text-danger
            .clearfix
            .col-lg-12.text-center
              #success
              %button#sendMessageButton.btn.btn-primary.btn-xl.text-uppercase{type: "submit"} Atualizar

/ Footer
%footer.footer
  .container
    .row.align-items-center
      .col-md-12
        %span.copyright Copyright © RT NFlix 2019

/ Portfolio Modals

- @profiles.each_with_index do |profile, index|
  .portfolio-modal.modal.fade{"aria-hidden" => "true", id: "#{profile.slug}", role: "dialog", tabindex: "-1"}
    .modal-dialog
      .modal-content
        .close-modal{"data-dismiss" => "modal"}
          .lr
            .rl
        .container
          .row
            .col-lg-12
              .modal-body
                /
                  Project Details Go Here
                %h2.text-uppercase= profile.name
                %p.item-intro.text-muted Lorem ipsum dolor sit amet consectetur.
                = image_tag "profile-image-#{index}.png", class: 'mx-auto img-fluid d-block'
                %p Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!
                %ul.list-inline
                  %li Date: January 2017
                  %li Client: Threads
                  %li Category: Illustration
                %button.btn.btn-primary{"data-dismiss" => "modal", type: "button"}
                  %i.fas.fa-times
                  Fechar

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    %meta{content: "", name: "description"}/
    %meta{content: "", name: "author"}/
    %title RT NFlix
    / Bootstrap core CSS
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / Custom fonts for this template
    %link{href: "https://fonts.googleapis.com/css?family=Montserrat:400,700", rel: "stylesheet", type: "text/css"}/
    %link{href: "https://fonts.googleapis.com/css?family=Kaushan+Script", rel: "stylesheet", type: "text/css"}/
    %link{href: "https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic", rel: "stylesheet", type: "text/css"}/
    %link{href: "https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700", rel: "stylesheet", type: "text/css"}/
    / Custom styles for this template
  %body#page-top
    / Navigation
    %nav#mainNav.navbar.navbar-expand-lg.navbar-dark.fixed-top
      .container
        %a.navbar-brand.js-scroll-trigger{href: "#page-top"} RT NFlix
        %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", type: "button"}
          Menu
          %i.fas.fa-bars
        #navbarResponsive.collapse.navbar-collapse
          %ul.navbar-nav.text-uppercase.ml-auto
            
            %li.nav-item
              %a.nav-link.js-scroll-trigger{href: "#portfolio"} Perfils
            %li.nav-item
              %a.nav-link.js-scroll-trigger{href: "#services"} Categorias
            %li.nav-item
              %a.nav-link.js-scroll-trigger{href: "#about"} Lançamentos
            %li.nav-item
              %a.nav-link.js-scroll-trigger{href: "#team"} Mais votados
            %li.nav-item
              %a.nav-link.js-scroll-trigger{href: "#contact"} Meus dados
            %li.nav-item
              = text_field_tag :q,'', placeholder: 'buscar por...', class: 'nav-link js-scroll-trigger search-at-top'
    = yield

app/views/layouts/devise.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1, shrink-to-fit=no", name: "viewport"}/
    %title= t('application_name')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body

    / Navigation
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
      .container
        = link_to t('application_name'), root_path, class: 'navbar-brand'
        %button.navbar-toggler{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", type: "button"}
          %span.navbar-toggler-icon
        #navbarResponsive.collapse.navbar-collapse

          %ul.navbar-nav.ml-auto
            = render partial: 'devise/shared/links_at_header'
    #master_container.container
      = flash_messages
      %header.jumbotron
        %h1.display-3 Bem vindo(a) a #{t('application_name')}
        %p.lead Chegou a hora de organizar o que você mais quer ver! Seus Filmes nunca ficarão tão em dia...
        = yield
    %footer.py-5.bg-dark
      .container
        %p.m-0.text-center.text-white
          ="Copyright © #{t('application_name')} #{Date.today.year}"

app/views/terms/index.html.haml
%h1 Terms#index
%p Find me in app/views/terms/index.html.haml